version: 2.1

jobs:
  build-and-push:
    parameters:
      kafka_version:
        type: string
      scala_version:
        type: string
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container image
          command: docker build -t app .

workflows:
  version: 2
  workflow:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              kafka_version: ["2.7.0", "2.6.1"]
              scala_version: ["2.13", "2.12"]
