version: 2.1

jobs:
  build-and-push:
    parameters:
      kafka_version:
        type: string
      scala_version:
        type: string
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container image
          command: |
            docker build \
              --build-arg KAFKA_VERSION=<< parameters.kafka_version >> \
              --build-arg SCALA_VERSION=<< parameters.scala_version >> \
              -t app .

workflows:
  version: 2
  workflow_scala-11-12-13:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              kafka_version: ["2.4.1", "2.4.0"]
              scala_version: ["2.13", "2.12", "2.11"]
  workflow_scala-11-12:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              kafka_version: ["2.3.1", "2.3.0", "2.2.2", "2.2.1", "2.2.0", "2.1.1", "2.1.0", "2.0.1", "2.0.0"]
              scala_version: ["2.12", "2.11"]
  workflow_scala-12-13:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              kafka_version: ["2.7.0", "2.6.1", "2.6.0", "2.5.1", "2.5.0"]
              scala_version: ["2.13", "2.12"]
